[General]
DisplayServer=x11
Numlock=none
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Theme]
Current=maldives
ThemeDir=/usr/share/sddm/themes
EnableAvatars=true
FacesDir=/usr/share/sddm/faces

[Users]
RememberLastSession=true
RememberLastUser=true
ReuseSession=true
MinimumUid=1000
MaximumUid=60513

[Wayland]
EnableHiDPI=true
