[General]
DisplayServer=wayland
InputMethod=qtvirtualkeyboard

[Wayland]
SessionDir=/usr/share/rice-sessions/wayland
CompositorCommand=start-hyprland -- --config /usr/share/sddm/hyprland.lua

[X11]
SessionDir=/usr/share/rice-sessions/x11
