[General]
InputMethod=qtvirtualkeyboard
GreeterEnvironment=QML2_IMPORT_PATH=/usr/share/sddm/themes/silent/components/,QT_IM_MODULE=qtvirtualkeyboard

[Theme]
Current=silent
EnableAvatars=true
FacesDir=/usr/share/sddm/faces

[Users]
RememberLastSession=true
RememberLastUser=true
