mode = "dark"

accent = "#38a7a7"
selection = "#102f2f"
muted = "#4f6267"

background = "#010202"
dark_background = "#000101"
darker_background = "#000000"
lighter_background = "#102f2f"

foreground = "#d8e4e6"
dark_foreground = "#596267"
light_foreground = "#8ea8ad"
bright_foreground = "#f0f7f8"

active_border_color = "#38a7a7"
active_tab_background = "#245b5c"

red = "#2f8d8d"
yellow = "#a5c8c9"
orange = "#5db2b4"
green = "#38a7a7"
cyan = "#56d8d8"
blue = "#257070"
magenta = "#245b5c"
brown = "#315e62"

bright_red = "#38a7a7"
bright_yellow = "#c3dfe1"
bright_green = "#56d8d8"
bright_cyan = "#8fe5e5"
bright_blue = "#2f8d8d"
bright_magenta = "#257070"
